version: '3.1'

services:
  backend:
    container_name: 'blind-piano-backend'
    image: node:18.11.0-alpine
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - .:/app
    working_dir: /app/backend
    command: 'yarn dev'
    tty: true
    environment:
      - PORT=${BACKEND_PORT}
      - TERM=xterm-256color

  frontend:
    container_name: 'blind-piano-frontend'
    image: node:18.11.0-alpine
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - .:/app
    working_dir: /app/frontend
    command: 'yarn dev'
    environment:
      - PORT=${FRONTEND_PORT}


