const instrumentOptions: Array<{ label: string; value: string }> = [
  { value: "FluidR3_GM-accordion", label: "Accordion" },
  { value: "FluidR3_GM-acoustic_bass", label: "Acoustic Bass" },
  { value: "FluidR3_GM-acoustic_grand_piano", label: "Acoustic Grand Piano" },
  {
    value: "FluidR3_GM-acoustic_guitar_nylon",
    label: "Acoustic Guitar (nylon)",
  },
  {
    value: "FluidR3_GM-acoustic_guitar_steel",
    label: "Acoustic Guitar (steel)",
  },
  { value: "FluidR3_GM-agogo", label: "Agogo" },
  { value: "FluidR3_GM-alto_sax", label: "Alto Sax" },
  { value: "FluidR3_GM-applause", label: "Applause" },
  { value: "FluidR3_GM-bagpipe", label: "Bagpipe" },
  { value: "FluidR3_GM-banjo", label: "Banjo" },
  { value: "FluidR3_GM-baritone_sax", label: "Baritone Sax" },
  { value: "FluidR3_GM-bassoon", label: "Bassoon" },
  { value: "FluidR3_GM-bird_tweet", label: "Bird Tweet" },
  { value: "FluidR3_GM-blown_bottle", label: "Blown Bottle" },
  { value: "FluidR3_GM-brass_section", label: "Brass Section" },
  { value: "FluidR3_GM-breath_noise", label: "Breath Noise" },
  { value: "FluidR3_GM-bright_acoustic_piano", label: "Bright Acoustic Piano" },
  { value: "FluidR3_GM-celesta", label: "Celesta" },
  { value: "FluidR3_GM-cello", label: "Cello" },
  { value: "FluidR3_GM-choir_aahs", label: "Choir Aahs" },
  { value: "FluidR3_GM-church_organ", label: "Church Organ" },
  { value: "FluidR3_GM-clarinet", label: "Clarinet" },
  { value: "FluidR3_GM-clavinet", label: "Clavinet" },
  { value: "FluidR3_GM-contrabass", label: "Contrabass" },
  { value: "FluidR3_GM-distortion_guitar", label: "Distortion Guitar" },
  { value: "FluidR3_GM-drawbar_organ", label: "Drawbar Organ" },
  { value: "FluidR3_GM-dulcimer", label: "Dulcimer" },
  { value: "FluidR3_GM-electric_bass_finger", label: "Electric Bass (finger)" },
  { value: "FluidR3_GM-electric_bass_pick", label: "Electric Bass (pick)" },
  { value: "FluidR3_GM-electric_grand_piano", label: "Electric Grand Piano" },
  {
    value: "FluidR3_GM-electric_guitar_clean",
    label: "Electric Guitar Clean",
  },
  {
    value: "FluidR3_GM-electric_guitar_jazz",
    label: "Electric Guitar Jazz",
  },
  {
    value: "FluidR3_GM-electric_guitar_muted",
    label: "Electric Guitar Muted",
  },
  {
    value: "FluidR3_GM-electric_piano_1",
    label: "Electric Piano 1",
  },
  {
    value: "FluidR3_GM-electric_piano_2",
    label: "Electric Piano 2",
  },
  {
    value: "FluidR3_GM-english_horn",
    label: "English Horn",
  },
  {
    value: "FluidR3_GM-fiddle",
    label: "Fiddle",
  },
  {
    value: "FluidR3_GM-flute",
    label: "Flute",
  },
  {
    value: "FluidR3_GM-french_horn",
    label: "French Horn",
  },
  {
    value: "FluidR3_GM-fretless_bass",
    label: "Fretless Bass",
  },
  {
    value: "FluidR3_GM-fx_1_rain",
    label: "Rain",
  },
  {
    value: "FluidR3_GM-fx_2_soundtrack",
    label: "Soundtrack",
  },
  {
    value: "FluidR3_GM-fx_3_crystal",
    label: "Crystal",
  },
  {
    value: "FluidR3_GM-fx_4_atmosphere",
    label: "Atmosphere",
  },
  {
    value: "FluidR3_GM-fx_5_brightness",
    label: "Brightness",
  },
  {
    value: "FluidR3_GM-fx_6_goblins",
    label: "Goblins",
  },
  {
    value: "FluidR3_GM-fx_7_echoes",
    label: "Echoes",
  },
  {
    value: "FluidR3_GM-fx_8_scifi",
    label: "Sci-Fi",
  },
  {
    value: "FluidR3_GM-glockenspiel",
    label: "Glockenspiel",
  },
  {
    value: "FluidR3_GM-guitar_fret_noise",
    label: "Guitar Fret Noise",
  },
  {
    value: "FluidR3_GM-guitar_harmonics",
    label: "Guitar Harmonics",
  },
  {
    value: "FluidR3_GM-gunshot",
    label: "Gunshot",
  },
  {
    value: "FluidR3_GM-harmonica",
    label: "Harmonica",
  },
  {
    value: "FluidR3_GM-harpsichord",
    label: "Harpsichord",
  },
  {
    value: "FluidR3_GM-helicopter",
    label: "Helicopter",
  },
  {
    value: "FluidR3_GM-honkytonk_piano",
    label: "Honky-tonk Piano",
  },
  {
    value: "FluidR3_GM-kalimba",
    label: "Kalimba",
  },
  {
    value: "FluidR3_GM-koto",
    label: "Koto",
  },
  { value: "FluidR3_GM-lead_1_square", label: "Lead 1 (square)" },
  { value: "FluidR3_GM-lead_2_sawtooth", label: "Lead 2 (sawtooth)" },
  { value: "FluidR3_GM-lead_3_calliope", label: "Lead 3 (calliope)" },
  { value: "FluidR3_GM-lead_4_chiff", label: "Lead 4 (chiff)" },
  { value: "FluidR3_GM-lead_5_charang", label: "Lead 5 (charang)" },
  { value: "FluidR3_GM-lead_6_voice", label: "Lead 6 (voice)" },
  { value: "FluidR3_GM-lead_7_fifths", label: "Lead 7 (fifths)" },
  { value: "FluidR3_GM-lead_8_bass__lead", label: "Lead 8 (bass/lead)" },
  { value: "FluidR3_GM-marimba", label: "Marimba" },
  { value: "FluidR3_GM-melodic_tom", label: "Melodic Tom" },
  { value: "FluidR3_GM-music_box", label: "Music Box" },
  { value: "FluidR3_GM-muted_trumpet", label: "Muted Trumpet" },
  { value: "FluidR3_GM-oboe", label: "Oboe" },
  { value: "FluidR3_GM-ocarina", label: "Ocarina" },
  { value: "FluidR3_GM-orchestra_hit", label: "Orchestra Hit" },
  { value: "FluidR3_GM-orchestral_harp", label: "Orchestral Harp" },
  { value: "FluidR3_GM-overdriven_guitar", label: "Overdriven Guitar" },
  { value: "FluidR3_GM-pad_1_new_age", label: "Pad 1 (new age)" },
  { value: "FluidR3_GM-pad_2_warm", label: "Pad 2 (warm)" },
  { value: "FluidR3_GM-pad_3_polysynth", label: "Pad 3 (polysynth)" },
  { value: "FluidR3_GM-pad_4_choir", label: "Pad 4 (choir)" },
  { value: "FluidR3_GM-pad_5_bowed", label: "Pad 5 (bowed)" },
  { value: "FluidR3_GM-pad_6_metallic", label: "Pad 6 (metallic)" },
  { value: "FluidR3_GM-pad_7_halo", label: "Pad 7 (halo)" },
  { value: "FluidR3_GM-pad_8_sweep", label: "Pad 8 (sweep)" },
  { value: "FluidR3_GM-pan_flute", label: "Pan Flute" },
  { value: "FluidR3_GM-percussive_organ", label: "Percussive Organ" },
  { value: "FluidR3_GM-piccolo", label: "Piccolo" },
  { value: "FluidR3_GM-piccolo", label: "Piccolo" },
  { value: "FluidR3_GM-pizzicato_strings", label: "Pizzicato Strings" },
  { value: "FluidR3_GM-recorder", label: "Recorder" },
  { value: "FluidR3_GM-reed_organ", label: "Reed Organ" },
  { value: "FluidR3_GM-reverse_cymbal", label: "Reverse Cymbal" },
  { value: "FluidR3_GM-rock_organ", label: "Rock Organ" },
  { value: "FluidR3_GM-seashore", label: "Seashore" },
  { value: "FluidR3_GM-shakuhachi", label: "Shakuhachi" },
  { value: "FluidR3_GM-shamisen", label: "Shamisen" },
  { value: "FluidR3_GM-shanai", label: "Shanai" },
  { value: "FluidR3_GM-sitar", label: "Sitar" },
  { value: "FluidR3_GM-slap_bass_1", label: "Slap Bass 1" },
  { value: "FluidR3_GM-slap_bass_2", label: "Slap Bass 2" },
  { value: "FluidR3_GM-soprano_sax", label: "Soprano Sax" },
  { value: "FluidR3_GM-steel_drums", label: "Steel Drums" },
  { value: "FluidR3_GM-string_ensemble_1", label: "String Ensemble 1" },
  { value: "FluidR3_GM-string_ensemble_2", label: "String Ensemble 2" },
  { value: "FluidR3_GM-synth_bass_1", label: "Synth Bass 1" },
  { value: "FluidR3_GM-synth_bass_2", label: "Synth Bass 2" },
  { value: "FluidR3_GM-synth_brass_1", label: "Synth Brass 1" },
  { value: "FluidR3_GM-synth_brass_2", label: "Synth Brass 2" },
  { value: "FluidR3_GM-synth_choir", label: "Synth Choir" },
  { value: "FluidR3_GM-synth_drum", label: "Synth Drum" },
  { value: "FluidR3_GM-synth_strings_1", label: "Synth Strings 1" },
  { value: "FluidR3_GM-synth_strings_2", label: "Synth Strings 2" },
  { value: "FluidR3_GM-taiko_drum", label: "Taiko Drum" },
  { value: "FluidR3_GM-tango_accordion", label: "Tango Accordion" },
  { value: "FluidR3_GM-telephone_ring", label: "Telephone Ring" },
  { value: "FluidR3_GM-tenor_sax", label: "Tenor Sax" },
  { value: "FluidR3_GM-timpani", label: "Timpani" },
  { value: "FluidR3_GM-tinkle_bell", label: "Tinkle Bell" },
  { label: "Tremolo Strings", value: "FluidR3_GM-tremolo_strings" },
  { label: "Trombone", value: "FluidR3_GM-trombone" },
  { label: "Trumpet", value: "FluidR3_GM-trumpet" },
  { label: "Tuba", value: "FluidR3_GM-tuba" },
  { label: "Tubular Bells", value: "FluidR3_GM-tubular_bells" },
  { label: "Vibraphone", value: "FluidR3_GM-vibraphone" },
  { label: "Viola", value: "FluidR3_GM-viola" },
  { label: "Violin", value: "FluidR3_GM-violin" },
  { label: "Voice Oohs", value: "FluidR3_GM-voice_oohs" },
  { label: "Whistle", value: "FluidR3_GM-whistle" },
  { label: "Woodblock", value: "FluidR3_GM-woodblock" },
  { label: "Xylophone", value: "FluidR3_GM-xylophone" },
];

export default instrumentOptions;
